server:
  port: 8080
  trustedPathPrefix: /internal/
  trustedPort: 8888

spring:
  mail:
    host: smtp.qq.com
    port: 25
    username: 1224178565@qq.com
    password: gjjcjvdvibdxgdba
    default-encoding: UTF-8

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    #    password: ENC(aZefON6YucZcoel3KsMkQA==)
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

jasypt:
  encryptor:
    #这里可以理解成是加解密的时候使用的密钥
    password: xunxunmi